version: "3.7"

services:
    app: 
        image: python:3
        command: bash -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=3000"
        ports: 
            - 3000:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            FLASK_APP: application.py
            FLASK_DEBUG: 1
        